### PR TITLE
‼️ Changes the project from a template to a node cli tool

### LINKED ISSUE #11: Add script to install with React
Add an installation script, `npx create-mern-app`, that installs the template as well as the main React template.

### PR DESCRIPTION
**Pull request by meerhamzadev**
Hey @cdthomp1 👋, I have implemented the create-mern-app CLI. A glimpse of the CLI is here

U1ntitled

555Untitled
11Untitled

This is the **client** side part

2222Untitled

1111Untitled

This is the **server** side part. When the CLI generates the server code you have to go to the server folder and run **npm install** to initialized node_modules/

2567Untitled

111111111111111Untitled

to use it with **npx** you are supposed to publish it on [npmjs registery](https://www.npmjs.com/)

to use it locally simply cd into the folder and run **npm link** in the terminal.

the structure of the command is:
 - create-mern-app [project-name]  via npm link
 - npx create-mern-app [project-name] via npx

### CODE REVIEW

**Comment by cdthomp1** [comment]
Fantastic! I will take a deeper look this weekend!

**Comment by cdthomp1** [comment]
@MeerHamza1421 Everything is looking good! I am going to get a pipeline setup so it will build and publish to npm before I merge. Great work!

**Comment by MeerHamza1421** [comment]
Thanks, @cdthomp1 🙌.

--------- Don't forget to add hacktoberfest-accepted label -----------

**Comment by cdthomp1** [comment]
I'm going to merge before the pipeline build :)

**Pull request merged**
